version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      
  simulator:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
      - CHANNEL_NAME=testfleet:jobs
      - INTERVAL_SECONDS=10
    depends_on:
      redis:
        condition: service_healthy
        
  test-subscriber:
    image: redis:7-alpine
    command: redis-cli -h redis SUBSCRIBE testfleet:jobs
    depends_on:
      - redis